### ISSUE TITLE
Lots of IInputConnectionWrapper warnings in the log

### ISSUE THREAD

**Issue by deakjahn** [rengwuxian/MaterialEditText#100]
Not a huge problem but it causes lots of similar entries in LogCat and creates noise:

    W/IInputConnectionWrapper(21214): getTextBeforeCursor on inactive InputConnection
    W/IInputConnectionWrapper(21214): getSelectedText on inactive InputConnection
    W/IInputConnectionWrapper(21214): getTextBeforeCursor on inactive InputConnection
    W/IInputConnectionWrapper(21214): getTextAfterCursor on inactive InputConnection

in `MaterialDialog.initText()`, use

      getText().clear();

to clear the text instead of passing null to `setText()`. Also, two lines below, check for an empty text before you set it repeatedly.

      if (!TextUtils.isEmpty(text))
        setText(text);

It's apparently these fast repeated `setText(null)`'s that lead to the warnings.

**Comment by deakjahn** [comment]
Nope, it doesn't help, it's already inside an `if`. I still get the warnings... Looking further...

**Comment by deakjahn** [comment]
Sorry, false alarm. It's somewhere else. Closing it down.

**Comment by Lawati97** [comment]
@deakjahn Kindly share with us how you solved this issue

**Comment by deakjahn** [comment]
@Lawati97 almost seven years (!) have passed since. Will it surprise you if I said I did't have the faintest idea? :-)
