### ISSUE TITLE
helperText over length text

### ISSUE THREAD

**Issue by jotaemepereira** [rengwuxian/MaterialEditText#101]
First of all, thank you for this library, is very useful!

I searched for this issue, but i didn't find anything, so here we go. The issue is what you see in the picture, the helperText overlaps length text.

![screen shot 2015-02-04 at 10 21 46 am](https://cloud.githubusercontent.com/assets/7924732/6040332/bd7d77cc-ac57-11e4-808b-f4d59643fcfb.png)

Is there some workaround for this issue?

Thanks!

**Comment by rengwuxian** [comment]
Hi @jotaemepereira ,

Sorry for the delay, a little busy these days.

About your issue, there's no workaround here, but I'll add the auto-newline support to the helper text, which has already been added to the error text. I'm gonna complete it in today, and notice you here as soon as it's done.

**Comment by rengwuxian** [comment]
Hi @jotaemepereira ,

1.8.3 has been released. This is fixed.

You can check the [latest library version](https://github.com/rengwuxian/MaterialEditText#download) now. 

_It may take several hours syncing to Maven Central._
