### ISSUE TITLE
Dotted underline make animation sluggish

### ISSUE THREAD

**Issue by pablow91** [rengwuxian/MaterialEditText#102]
I have few MaterialEditText items on one screen. When I disable them the underline changes from straight line to dotted line. It cause serious performance problem and I cannot animate entering or exiting this screen without having huge lag.

Please draw dotted lines in more optimal way.

**Comment by rengwuxian** [comment]
Hi, @pablow91 ,

Sorry for the delayed reply. `MaterialEditText` 2.0 is gonna be released in about 2 weeks. I'll do some performance optimization work, including the anitation's performance.

**Comment by rengwuxian** [comment]
Hi @pablow91 ,

2.0.3 has been released. Could you feel more fluid now?

You can check the [latest library version](https://github.com/rengwuxian/MaterialEditText#download) now.
