### ISSUE TITLE
the setError method not aligned with edittext

### ISSUE THREAD

**Issue by gustavomc** [rengwuxian/MaterialEditText#106]
when i use the method setError it shows the error message but not aligned to the edittext it shows with padding like 16dp

**Comment by rengwuxian** [comment]
Hi @gustavomc ,

This is by design. different developers have different requirements about this. And I decide to let MaterialEditText work this way, at least for now.

**Comment by BabuinGH** [comment]
@gustavomc , I would like to set the error message aligned with edittext, how can I achieve this ?
