### ISSUE TITLE
onFocusChangeListener does not work

### ISSUE THREAD

**Issue by chintanshah24** [rengwuxian/MaterialEditText#107]

**Comment by sey** [comment]
Can you be more specific? 
It works ok for me with 1.8.2 version in both cases (blur and focus).

**Comment by rengwuxian** [comment]
Hi @chintanshah24 ,

1.8.3 has been released. This is fixed.

You can check the [latest library version](https://github.com/rengwuxian/MaterialEditText#download) now. 

_It may take several hours syncing to Maven Central._
