### ISSUE TITLE
Enhancenments

### ISSUE THREAD

**Issue by jandrop** [rengwuxian/MaterialEditText#111]
- EditText disabled without no dots option 
- FloatingLabel allways highlight
- Change color of disabled EditText

**Comment by rengwuxian** [comment]
Hi @jandrop ，

I'm planning about the `MaterialEditText` 2.0. I'll consider about you advices. Thanks!

**Comment by RustamG** [comment]
Hi @rengwuxian,

Thank you so much for this library! Can we have customizable alpha that you apply to hint and base color? I mean all these hardcoded ```0x44000000``` that applied to colors. Can we made this value customizable?

**Comment by rengwuxian** [comment]
@RustamG Yeah. v2 will introduce complete customization options.

**Comment by jandrop** [comment]
This is great!

**Comment by rengwuxian** [comment]
Hi @jandrop ,

2.0.3 has been released. `met_floatingLabelAlwaysShown` has been introduced. And you can use `met_textColor` to set you text color with ColorStateList, of course, including the disabled text. But about the bottom line's dots style, it's not introduced, since it's not following Google's Material Design Spec.

You can check the [latest library version](https://github.com/rengwuxian/MaterialEditText#download) now.

**Comment by rengwuxian** [comment]
Hi @RustamG ,

Just use v2.0.3 and try `met_textColor`. Thanks!

**Comment by RustamG** [comment]
@rengwuxian Great job! Thank you, I'll try it.

**Comment by RustamG** [comment]
@rengwuxian , 
In order to achieve my goal (to have floating label with specific color no matter of control state) I have to call setFocusFraction(1). Will you make this parameter customizable through xml attribute?

**Comment by rengwuxian** [comment]
Don't use highlight mode in this case. Normal mode is what you want, right?

**Comment by RustamG** [comment]
Yeah, I use Normal mode.

**Comment by rengwuxian** [comment]
Have you tried `floatingLabelTextColor` ?

**Comment by RustamG** [comment]
Yes, I use both ```floatingLabelTextColor``` and ```setFocusFraction(1)```. If I use ```floatingLabelTextColor``` without calling ```setFocusFraction(1)``` then color of floating label is changed when MaterialEditText doesn't have focus.

**Comment by jandrop** [comment]
@rengwuxian works like a charm

**Comment by rengwuxian** [comment]
@RustamG Sorry for the delayed reply. I can't repro your issue. Could you send me a simple sample project so I can get deeper into it?

**Comment by RustamG** [comment]
@rengwuxian Never mind. Everything works great. Thank you :)
