### ISSUE TITLE
Style

### ISSUE THREAD

**Issue by aquintiliano** [rengwuxian/MaterialEditText#114]
It doesn't work with style.xml
It should work?

**Comment by avrahamshukron** [comment]
It does work.

Just don't specify the namespace for the attribute, like that:
`<item name="baseColor">@color/my_color</item>`

**Comment by aquintiliano** [comment]
thanks, I'll try

**Comment by aquintiliano** [comment]
is there somehow to apply the style to all views in the project??

**Comment by sey** [comment]
I think you can use something like that (no tested)
```xml
<resources>
	<style name="AppTheme" parent="Theme.AppCompat.Light.DarkActionBar">
		<item name="editTextStyle">@style/EditTextStyle</item>
	</style>
	<style name="EditTextStyle" parent="Widget.AppCompat.EditText">
	    <item name="floatingLabel">highlight</item>
	</style>
</resources>
```

**Comment by aquintiliano** [comment]
Sadly it doesn't work... I think it is easy to make it works, may you implement it? Or, if you want, I can help (I can try, at least)

**Comment by rengwuxian** [comment]
Hi all,

I don't know much about this. Please let us know if you got some idea about @aquintiliano 's request -- to automatically apply a uniform style to all instances in the project. Thanks!
