### ISSUE TITLE
Problems with floating label

### ISSUE THREAD

**Issue by cristiammercado** [rengwuxian/MaterialEditText#115]
When you write two words or more, and then you erase one of them, the floating label disappears.

For example, when I was writing "Hi People", and erase until "Hi ", the floating label disappears, but there are still words in the text field.

Any solution?

**Comment by sey** [comment]
What is your MaterialEditText configuration?

**Comment by cristiammercado** [comment]
I was testing the app in Google Play Store...

**Comment by sey** [comment]
What's your device and OS version? I am on a Nexus 5 with Android 5 and I have the expected behavior. I can't reproduce your problem.

**Comment by rengwuxian** [comment]
Hi @cristiammercado ,

Could you show me your OS version and your device model. I can't reproduce your problem, too.
