### ISSUE TITLE
Set floating label text size over xml

### ISSUE THREAD

**Issue by vyscond** [rengwuxian/MaterialEditText#116]
can we have it? :)

**Comment by crysan** [comment]
+1

**Comment by rengwuxian** [comment]
Hi @vyscond and @crysan ,

Try `app:floaingLabelTextSize`.

Thanks!

**Comment by vyscond** [comment]
Thank you man! :)

**Comment by crysan** [comment]
compile 'com.rengwuxian.materialedittext:library:1.8.2'

    <com.rengwuxian.materialedittext.MaterialEditText
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:id="@+id/tAddPoint_desc"
        android:hint="@string/dialog_label_desc"
        android:textSize="18dp"
        app:floaingLabelTextSize="14dp"
        app:floatingLabelText="@string/dialog_label_desc"
        app:floatingLabel="highlight"
        app:hideUnderline="false"/>

error: No resource identifier found for attribute 'floaingLabelTextSize' in package

**Comment by rengwuxian** [comment]
My fault. I missed a 't' character. It should be `floatingLabelTextSize`, not 'floaingLabelTextSize`.

**Comment by crysan** [comment]
Yes, I just did not pay attention. 
Thank U!
