### ISSUE TITLE
Attribute to set alpha level of base and primary colors

### ISSUE THREAD

**Issue by vyscond** [rengwuxian/MaterialEditText#118]
I thinks it will be useful if we can change the levels of alpha applied!

**Comment by onyekaa** [comment]
+1

**Comment by peternguyen88** [comment]
I need this too

**Comment by avrahamshukron** [comment]
+1000!

**Comment by vyscond** [comment]
i think it's time to fork this up! the only problem to me is that i don't have any idea how to make my (future) fork available on maven .-.

**Comment by avrahamshukron** [comment]
@vyscond There are many guides available online.
Start at http://maven.apache.org/guides/mini/guide-central-repository-upload.html

**Comment by rengwuxian** [comment]
Hi all,

Sorry for the delayed reply, I've been busy these days.

MaterialEditText 2.0 is about to be released, with much more customization access. But I can't spend much time on this every day. The v2.0 will come in about 2 weeks. You could wait for me, or just fork this library and make changes as what you want. Thanks!

**Comment by avrahamshukron** [comment]
@rengwuxian, First of all - Thank you very much for this awesome library and for the time you devote for it!

It would be really great if you could push the changes you have right now to a dedicated "2.0" branch or something.

This way we could see what are the changes and features you are planing, so we could avoid re-implementing them or conflicting them in our forks.

Thank you very much!

**Comment by rengwuxian** [comment]
@avrahamshukron I've just created the branch and got ready to work on it.

The branch's name is `v2`. https://github.com/rengwuxian/MaterialEditText/tree/v2

**Comment by rengwuxian** [comment]
Hi all,

2.0.3 has been released, introducing a unified prefix 'met_'

You can check the [latest library version](https://github.com/rengwuxian/MaterialEditText#download) now.

**Comment by rengwuxian** [comment]
Forgot to mention, you can customize every part's color now! check the new wiki page!

**Comment by peternguyen88** [comment]
Can you show an example how to change the alpha level of Floating Label? I haven't figured out how to do that.

**Comment by cokeby190** [comment]
+1
