### ISSUE TITLE
setBaseColor() doesn't works in Java

### ISSUE THREAD

**Issue by LorenzoZanotto** [rengwuxian/MaterialEditText#119]
I'm trying to set EditText Base Color via Java,
I'm using the classical approach:

view.setBaseColor()

but it doesn't works (the method turns red).
How can I solve this?

**Comment by Moter8** [comment]
Example LoginActivity.java:
```java
[...] // other imports
import com.rengwuxian.materialedittext.MaterialEditText;

import butterknife.ButterKnife;
import butterknife.InjectView;

public class LoginActivity extends ActionBarActivity {

    @InjectView(R.id.usernameField) com.rengwuxian.materialedittext.MaterialEditText mUsernameField;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_login);
        ButterKnife.inject(this);

        mUsernameField.setBaseColor(Color.parseColor("#FF00897B")); // some blue-ish color
    }
```

Using Butterknife you can make this really simple. You just annotate the injections once and they get loaded automatically with `ButterKnife.inject(this);`. 
You can then set the EditText's properties to whatever you want :100:

**Comment by LorenzoZanotto** [comment]
Thank you man, I'll give a try!

**Comment by rengwuxian** [comment]
Hi @LorenzoZanotto ,

Have you solved this?

**Comment by Moter8** [comment]
@LorenzoZanotto @rengwuxian 
By the way, I've added an entry to the Wiki with [layout and code examples](https://github.com/rengwuxian/MaterialEditText/wiki/Layout-and-Code-Example).

**Comment by LorenzoZanotto** [comment]
@rengwuxian yeah, thank you, ButterKnife class done the work!

**Comment by Moter8** [comment]
@LorenzoZanotto Pro tip: There is a "close issue" button at the bottom :)

**Comment by rengwuxian** [comment]
Thanks, @Moter8 , for the new wiki page. BTW, I'm gonna find a way to solve the preview view issue that you've mentioned. : )
