### ISSUE TITLE
Clipping when ViewGroup height is small

### ISSUE THREAD

**Issue by gtcompscientist** [rengwuxian/MaterialEditText#120]
![screen shot 2015-02-26 at 3 06 07 pm](https://cloud.githubusercontent.com/assets/230875/6400729/077bb168-bdc9-11e4-9ac8-ac98fcb35343.png)

As you can see, the text within the EditText (A MaterialMultiAutoCompleteTextView, in this case) is being clipped rather dramatically. I believe it's being caused by the floating label, but I can't prove it. The floating label itself is turned off, and I've tested with several other variables, including setting the Paddings to 0. But nothing seems to help this clipping.

Any suggestions?

**Comment by rengwuxian** [comment]
Hi @gtcompscientist ,

You're right. This is due to the floating label. Why not just hide the floating label or increase the wrapper layout's height?

**Comment by gtcompscientist** [comment]
The floating label is set to None, but it's still blocking the view.

**Comment by rengwuxian** [comment]
Looks weird. could you send me a sample project, please?

**Comment by gtcompscientist** [comment]
Sample project looks like this: 
![screenshot_2015-03-11-14-09-06](https://cloud.githubusercontent.com/assets/230875/6603399/4531b6c2-c7f8-11e4-8982-36742412596e.png)

APK and source for download: https://www.dropbox.com/sh/78sd31mawe0vo2j/AADvg7f2SwF9LrecQoK18xWra?dl=0

It's very easy to reproduce by setting a fixed height on the edit box.

**Comment by gtcompscientist** [comment]
If the floating label will actually disappear/not clip the text, that would be a HUGE help, and if we could configure the underline and paddings, it would be perfect.

**Comment by rengwuxian** [comment]
Found the issue. You should set the height `wrap_content` or a size equal to or larger than 48dp, which is the least size that Material Design Spec suggests for a text field (or say, EditText in Android).

**Comment by gtcompscientist** [comment]
Unfortunately, that's not an option in this particular scenario.

**Comment by rengwuxian** [comment]
Do you mean you have to set the height to 40dp? `MaterialEditText` doesn't support height less than 48dp. But you can download the project and do some change for youself. The code is not that complicated.
