### ISSUE TITLE
Add RadioButton Support?

### ISSUE THREAD

**Issue by thereallukesimpson** [rengwuxian/MaterialEditText#121]
Awesome library, but all my forms also contain radio buttons. I will be writing the code to make the radio button behavior consistent with the EditText fields, namely label highlighting, and thought it might be nice to include it in this library.

Please let me know and I'll add a pull request.

**Comment by avrahamshukron** [comment]
This request has nothing to do with this library...
If you can write it, start another library...

**Comment by rengwuxian** [comment]
Hi @thereallukesimpson ,

The integration of RadioButton will complicate this library, and as @avrahamshukron says, this is just an `EditText` library, which should not introduce the RadioButton integration. Or what do you think about it?

**Comment by thereallukesimpson** [comment]
Hi @rengwuxian,
In a perfect world they would be in the same library (or the Android SDK!) but I understand the need to limit the scope of this library. I'll see about adding a separate library.
Thanks,
Luke
