### ISSUE TITLE
Attribute "typeface" has already been defined

### ISSUE THREAD

**Issue by mehhh** [rengwuxian/MaterialEditText#122]
Same kind of issue has with the attribute "primaryColor". I use a lot of libraries but i am almost sure that the one who is causing the conflict with MaterialEditText is android-betterpickers from Derek Brameyer.

**Comment by anshulagarwal2k** [comment]
Any solution for this issue?

**Comment by mehhh** [comment]
Got it working by adding the Library as a module to the app and manually changing the name of the attribute "typeface" to another like "typefaceAlt". So i can't count it as resolved. A good way to resolve this and other issues like this one, is doing as some libraries already do and that is, every library specific attribute as an unique prefix. For example for MaterialEditText Library, every added attribute would start with the initials of MaterialEditText (met) and some more specific if necessary. 

primaryColor -> metPrimaryColor
typeface -> metTypeface

**Comment by rengwuxian** [comment]
Hi @mehhh ,

Thanks for you suggestion. I'll try to find an elegant way to solve these stuff, and add it to the coming v2.0. (v2.0 is gonna be released this weekend.)

**Comment by rengwuxian** [comment]
Hi all,

2.0.3 has been released, introducing a unified prefix 'met_'

You can check the [latest library version](https://github.com/rengwuxian/MaterialEditText#download) now.
