### ISSUE TITLE
Error text moves widgets below

### ISSUE THREAD

**Issue by crisi** [rengwuxian/MaterialEditText#124]
Is there a way to prevent the error text from moving down the widgets below? I know I could prereserve that space by setting the helper text to an empty string but when doing this programmatically the widgets below are also moved down.

Regards, Chris

**Comment by crisi** [comment]
I prevented this by setting the following attributes on my text field in my layout xml:

	app:helperText=""
	app:helperTextAlwaysShown="true"

**Comment by rengwuxian** [comment]
minBottomTextLines=1

I know this attribute looks weird. ^_^
