### ISSUE TITLE
Change color where edit text hasn't focus

### ISSUE THREAD

**Issue by daniruizcamacho** [rengwuxian/MaterialEditText#126]
Hi! I put this edit text but I can't change the color when the edit text hasn't focus. Always it takes a lighter color that background color of layout.

Is possible change the color when the edit text hasn't the focus?

**Comment by rengwuxian** [comment]
Hi @daniruizcamacho ,

Do you mean the EditText's bottom line's color, or the text's font color, or something else's color?

**Comment by daniruizcamacho** [comment]
I refer to Bottom line's color and text's font color. Thanks

**Comment by rengwuxian** [comment]
Hi @daniruizcamacho ,

Do you mean the text's font color? Or the bottom line's color? Or something else?

**Comment by rengwuxian** [comment]
You can use baseColor to custom the bottom line's color under non-focus state; About the text color, do you mean you wanna define different colors for it under non-focus state, not just to turn down its alpha value?

**Comment by daniruizcamacho** [comment]
I try this but doesn't work. I put my code here.
I am trying to change this color when the edit text hasn't focus. I prefer other color more lighter or dark. 
Thanks.

```
<LinearLayout
            android:id="@+id/titleLayout"
            android:orientation="vertical"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_below="@id/toolbar"
            android:background="@color/md_teal_600">

            <com.rengwuxian.materialedittext.MaterialEditText
                android:id="@+id/title_edit_text"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:layout_marginLeft="@dimen/dimen20"
                android:layout_marginRight="@dimen/dimen20"
                android:singleLine="true"
                android:textSize="@dimen/title_text_size"
                android:hint="@string/title_hint_text"
                android:textCursorDrawable="@null"
                app:baseColor="@color/white"
                app:floatingLabel="highlight"
                app:floatingLabelTextSize="@dimen/highlight_text_size"
                app:primaryColor="@color/md_teal_A700"
                app:singleLineEllipsis="false"
                />

        </LinearLayout>
```
![alt text](http://i58.tinypic.com/25ks8kz.png)

**Comment by rengwuxian** [comment]
Got it. MaterialEditText use's Material Design's rule to automatically adjust the alpha values for every part. It adjust the bottom lines alpha to make it looks translucent. If you want to set a color to the bottom line accurately, just wait for about 2 days. v2.0 is about to come out, with many customizing options.

**Comment by rengwuxian** [comment]
Hi all,

2.0.3 has been released, try `met_textColor` and `met_textColorHint`.

You can check the [latest library version](https://github.com/rengwuxian/MaterialEditText#download) now.
