### ISSUE TITLE
Gradle execution not working 

### ISSUE THREAD

**Issue by pratikbutani** [rengwuxian/MaterialEditText#127]
Its not working with `compile 'com.rengwuxian.materialedittext:library:1.8.3'`

**Comment by rengwuxian** [comment]
Hi @pratikbutani ,

I just checked the v1.8.3 in the Maven Centrual, and it was OK. So you'd better double check your build scripts.

Thanks!

**Comment by pratikbutani** [comment]
Thanks for your reply. I have just changed gradle execution online from
offline work in HTTP proxy.

Now Its works finally.

On Wed, Mar 11, 2015 at 9:25 PM, Kai Zhu <notifications@github.com> wrote:

> Hi @pratikbutani <https://github.com/pratikbutani> ,
>
> I just checked the v1.8.3 in the Maven Centrual, and it was OK. So you'd
> better double check your build scripts.
>
> Thanks!
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/rengwuxian/MaterialEditText/issues/127#issuecomment-78292090>
> .
>



-- 
---------------------------------
*Thanks & Regards,*

*Pratik Butani*

*MCA,*

*Rajkot - Gujarat*

*Contact - (+91) 88 66 22 45 46*

*http://about.me/pratikbutani <http://about.me/pratikbutani>*

**Comment by rengwuxian** [comment]
Great!
