### ISSUE TITLE
Posibility to clean input

### ISSUE THREAD

**Issue by mseroczynski** [rengwuxian/MaterialEditText#129]
Hey there. It would be really nice if this library provided some simple X image button that would clear current input, i'm thinking about adding this - would it be accepted? Or is it there already and i'm missing it?

**Comment by rengwuxian** [comment]
#93 has mentioned this. And it's on the way~ I'll add this feature within 2 days.

**Comment by mseroczynski** [comment]
@rengwuxian Could you please once again ensure it's coming :)?

**Comment by mseroczynski** [comment]
@rengwuxian Could you please ensure us you're alive :)?

**Comment by rengwuxian** [comment]
Yes I am haha. Maybe you've not noticed that v2.0.0-SNAPSHOT has already added this. Try `met_clearButton="true"`. There's no doc for 2.0 now. Been out of GitHub and my gmail for several days. So you see, I'm alive~

**Comment by rengwuxian** [comment]
Hi all,

2.0.3 has been released.

You can check the [latest library version](https://github.com/rengwuxian/MaterialEditText#download) now.

**Comment by mseroczynski** [comment]
Yeah computer science!
