### ISSUE TITLE
FLoating label does not appear

### ISSUE THREAD

**Issue by fipil** [rengwuxian/MaterialEditText#133]
Hi, I'm trying to use your library but I cannot make it working.
The floating label doesn't appear.
What I did:
1. I'm using Android Studio 1.1.0
2. I added: compile 'com.rengwuxian.materialedittext:library:1.8.3' to my build.gradle
3. I addded your declare-styleable to my attrs.xml
4. I added your dimensions to my dimens.xml.
5. I added this to my fragment layout:
...
&lt;com.rengwuxian.materialedittext.MaterialEditText
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:hint="Floating Label"
            app:met_floatingLabel="normal"
            android:layout_marginTop="20dp"/&gt;
...

When I run my app and open the activity with the fragment containing the layout it shows the component with hint text "Floating Label". I start typing and the hint text disappears but the floating label doesnt appear.

Please did I forget something?
Thanks!
Fipil

**Comment by fipil** [comment]
I probably solved it: I was missing the NineOldAndroids dependency in my build.gradle.
After adding it works.

BUT: I noticed that the NineOldAndroids is now DEPRECATED. Please, are you going to replace it by something else?

Anyway, this is great library! Thank you!.
Fipil.

**Comment by JVillella** [comment]
I found that I didn't need to add NineOldAndroids as a dependency - MaterialEditText has that defined in its own build.gradle. Also, nowadays you actually don't need to copy attrs, and dimen from the librararies you are using. In your layout files that use MaterialEditText add this `xmlns:app="http://schemas.android.com/apk/res-auto"`.

**Comment by fipil** [comment]
Thanks for help Julian. Strange thing is that Floating label did not appear untli I add thenNineOldAndroid dependency to my build.gradle. Just after that it started working.
