### ISSUE TITLE
Change floatingLabelTextColor. How?

### ISSUE THREAD

**Issue by UnateD** [rengwuxian/MaterialEditText#134]
Good afternoon. I need to change floatingLabelTextColor, but for this function is not provided. How can I do this? Something like Higline flag, but not in focus. I need set my color for floating lable permanent.

**Comment by rengwuxian** [comment]
Hi @UnateD ,

You can use v2.0.0 snapshot, or wait for the v2.0 release version. It won't be too long.

**Comment by bigforcegun** [comment]
How i can change floatingLabelTextColor in not focused state?
It's changed only is i change app theme from Theme.AppCompat.Light to dark.
I try, but I could not find style attribute in theme and source code of library, which can change that color.

**Comment by Rainer-Lang** [comment]
Great news - thanks.

**Comment by rengwuxian** [comment]
Hi all,

2.0.3 has been released, introducing the attribute `met_floatingLabelTextColor`.

You can check the [latest library version](https://github.com/rengwuxian/MaterialEditText#download) now.
