### ISSUE TITLE
No Resource Identifier found for .... (2.0.0-SNAPSHOT)

### ISSUE THREAD

**Issue by danielwilson1702** [rengwuxian/MaterialEditText#136]
I can't use 1.8.2 because the focus listener doesn't seem to work, I can't use 1.8.3 because of the weird typeface duplicate issue, and 2.0.0 seems to have totally broken the library!

        <com.rengwuxian.materialedittext.MaterialEditText
            android:id="@+id/create_post_editText"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:hint="@string/community_post_enter_text"
            android:imeOptions="actionSend"
            android:inputType="textCapSentences|textMultiLine"
            android:focusableInTouchMode="true"
            android:clickable="true"
            android:focusable="true"
            app:floatingLabel="highlight"
            app:maxCharacters="500"
            app:primaryColor="@color/accent"/>

This works in 1.8.2, but now none of the app:_____ properties are recognized! Any suggestions?

**Comment by Arkezis** [comment]
I think in 2.0.0 it's app:met_XXXXX (with XXXX the property).

**Comment by danielwilson1702** [comment]
You are right! Thanks, from question #122 I even tried a met prefix but not met_
