### ISSUE TITLE
Error compile No resource identifier found for attribute...

### ISSUE THREAD

**Issue by ygorcesar** [rengwuxian/MaterialEditText#139]
I have tried execute my activity with this layout:

<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/lib"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="#aaaaaa"
    android:orientation="vertical"
    android:paddingBottom="@dimen/activity_vertical_margin"
    android:paddingLeft="@dimen/activity_horizontal_margin"
    android:paddingRight="@dimen/activity_horizontal_margin"
    android:paddingTop="@dimen/activity_vertical_margin"
    tools:context=".MainActivity">

    <com.rengwuxian.materialedittext.MaterialEditText
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_centerHorizontal="true"
        android:layout_centerVertical="true"
        android:ems="10"
        android:hint="User Name"
        android:inputType="textPersonName"
        app:met_floatingLabel="normal"
        app:met_maxCharacters="20" />

    <com.rengwuxian.materialedittext.MaterialEditText
        android:id="@+id/passwordField"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_alignLeft="@+id/usernameField"
        android:layout_alignStart="@+id/usernameField"
        android:layout_below="@+id/usernameField"
        android:layout_marginTop="28dp"
        android:ems="10"
        android:hint="Password"
        android:inputType="textPassword"
        app:met_floatingLabel="highlight"
        app:met_minCharacters="6" />
</LinearLayout>

But return this error:

Error:(15) No resource identifier found for attribute 'met_floatingLabel' in package 'br.com.iscariot.exampleedittextmaterial'
Error:(15) No resource identifier found for attribute 'met_maxCharacters' in package 'br.com.iscariot.exampleedittextmaterial'
Error:(26) No resource identifier found for attribute 'met_floatingLabel' in package 'br.com.iscariot.exampleedittextmaterial'
Error:(26) No resource identifier found for attribute 'met_minCharacters' in package 'br.com.iscariot.exampleedittextmaterial'
Error:Execution failed for task ':app:processDebugResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files\Java\android-sdk\build-tools\21.1.2\aapt.exe'' finished with non-zero exit value 1

Can anyone help me with this error?

My build.gradle:
dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile 'com.android.support:appcompat-v7:22.0.0'
    compile 'com.rengwuxian.materialedittext:library:1.8.3'
}

**Comment by athornz** [comment]
I think the met_ prefixes have only been added in 2.0. Try removing them.
