### ISSUE TITLE
Gradle can't download your library 2.0.0

### ISSUE THREAD

**Issue by ygorcesar** [rengwuxian/MaterialEditText#141]
I write " compile 'com.rengwuxian.materialedittext:library:2.0.0-SNAPSHOT'  '' 
in my build.gradle file, but it prompts this: 
"Failed to resolve: com.rengwuxian.materialedittext:library:2.0.0-SNAPSHOT''

Can anyone help me with this error?

**Comment by danielgomezrico** [comment]
You need to add

repositories {
  // Needed for com.rengwuxian.materialedittext
  maven { url 'https://oss.sonatype.org/content/groups/public' }
}
dependencies {
....
}

into your gradle file, just behind the dependencies...

**Comment by cypressious** [comment]
What @danielgomezrico said and also change your dependency to

```compile ('com.rengwuxian.materialedittext:library:2.0.+')```

**Comment by rengwuxian** [comment]
Hi all,

2.0.3 has been released.

You can check the [latest library version](https://github.com/rengwuxian/MaterialEditText#download) now.
