### ISSUE TITLE
Temporary disabling floating label appear animation

### ISSUE THREAD

**Issue by JKMirko** [rengwuxian/MaterialEditText#142]
Is it possible to temporarily disable floating label animation?

On one screen I set text to some input fields programmatically and input fields floating labels get animated. This is done in *onCreateView* because I want to pre-fill some data and in this case I would like to disable animation. Is this possible?

**Comment by rengwuxian** [comment]
Hi all,

2.0.3 has been released. Try `setFloatingLabelAnimating(false)`.

You can check the [latest library version](https://github.com/rengwuxian/MaterialEditText#download) now.
