### ISSUE TITLE
Default base color is calculated incorrectly

### ISSUE THREAD

**Issue by glodos** [rengwuxian/MaterialEditText#144]
Here is a code snippet from the widget initialization:
```java
// retrieve the default baseColor 
int defaultBaseColor; 
TypedValue baseColorTypedValue = new TypedValue(); 
context.getTheme().resolveAttribute(android.R.attr.windowBackground, baseColorTypedValue, true); 
defaultBaseColor = Colors.getBaseColor(baseColorTypedValue.data); 
```

You shouldn't use windowBackground attribute to determine whether the theme is dark or light. If background is a drawable, this code will produce wrong output. In my case all text fields became white after I changed my window background from color to a drawable, despite the light theme.

Imo, more reliable way would be to read the textColorPrimary attribute, which is always a color.

**Comment by rengwuxian** [comment]
Hi @glodos ,

2.0.3 has been released. Now default value for baseColor is always black.

You can check the [latest library version](https://github.com/rengwuxian/MaterialEditText#download) now.
