### ISSUE TITLE
Three dots with app:met_singleLineEllipsis="true" are always shown

### ISSUE THREAD

**Issue by christian160984** [rengwuxian/MaterialEditText#145]
Although my Editttext is empty, three dots below on the left are shown

    <com.example.MaterialEditText
                            android:layout_width="match_parent"
                            android:layout_height="wrap_content"
                            android:layout_gravity="center_vertical"
                            android:gravity="center"
                            android:inputType="text"
                            android:hint="@string/name"
                            app:met_maxCharacters="25"
                            app:met_singleLineEllipsis="true"
                            app:met_floatingLabel="highlight"
                            app:met_floatingLabelTextSize="15sp"
                            android:textCursorDrawable="@drawable/cursor"
                            android:nextFocusDown="@+id/perfil_edittext_altura"
                            android:textSize="30sp" />

**Comment by rengwuxian** [comment]
Hi @christian160984 ,

I just tried this and didn't repro this. Could you provide some more details?
