### ISSUE TITLE
Build Failed, could not load maven meta-data

### ISSUE THREAD

**Issue by nbau21** [rengwuxian/MaterialEditText#148]
Let me start by saying I had the app working on my phone for several days now. This error only showed up within the last hour, and building was fine before that.

I can't really find anyone else with the same errors. Help?

My entire error message:

Error:A problem occurred configuring project ':app'.

Could not resolve all dependencies for configuration ':app:_debugCompile'. Could not resolve com.rengwuxian.materialedittext:library:2.0.0-SNAPSHOT. Required by: ZLedger:app:unspecified Unable to load Maven meta-data from https://jitpack.io/com/rengwuxian/materialedittext/library/2.0.0-SNAPSHOT/maven-metadata.xml. Could not GET 'https://jitpack.io/com/rengwuxian/materialedittext/library/2.0.0-SNAPSHOT/maven-metadata.xml'. Received status code 400 from server: Expecting: /com/github/user/repo/tag/repo-tag.pom

**Comment by LachlanGoodhew** [comment]
I'm getting the same thing. 
When I browse to https://oss.sonatype.org/content/groups/public/com/rengwuxian/materialedittext/library/2.0.0-SNAPSHOT/ I can't see any pom file which I think is the issue.
When I use the non snapshot builds (2.0.0, 2.0.1, 2.0.2, 2.0.3) I get errors when trying to use floatingLabel.

Any help is appreciated.

**Comment by LachlanGoodhew** [comment]
compile 'com.rengwuxian.materialedittext:library:2.0.3'

changed floatingLabel to met_floatingLabel and everything works fine.

**Comment by nbau21** [comment]
Thank you, it works. What does SNAPSHOT mean and why did it just suddenly not work? Is it advised not to use snapshot builds?

**Comment by squeeish** [comment]
http://stackoverflow.com/questions/5901378/what-exactly-is-a-maven-snapshot-and-why-do-we-need-it

In a nutshell, snapshot builds are not release builds. In this case the README.md hasn't been updated yet after rengwuxian released 2.0.3.

**Comment by rengwuxian** [comment]
Hi all,

2.0.3 has been released, introducing a unified prefix 'met_'

You can check the [latest library version](https://github.com/rengwuxian/MaterialEditText#download) now.
