### ISSUE TITLE
app:met_floatingLabelTextColor="@color/text_secondary" is too dark

### ISSUE THREAD

**Issue by Rainer-Lang** [rengwuxian/MaterialEditText#150]
Is use textsecondary like in the guidelines mentioned with 54% of 000000: #8a000000

But the floating label is too dark. All other labels (simple TextView) with this color are light grey.

**Comment by elwoodxblues** [comment]
I'm experiencing the same issue with this.

**Comment by jonathanlmarsh** [comment]
It looks like the actually guidelines specification for 54% Black is intended to be in CMYK (0, 0, 0, 54) which in RGB is #ff757575.

**Comment by Rainer-Lang** [comment]
@jonathanlmarsh Do you have a link to the guidelines where this is written?

**Comment by jonathanlmarsh** [comment]
@Rainer-Lang It unfortunately is not spelled out in the guideline. But if you do some digging around the material style xml's you will find that they do not use any transparencies for the font colors. If you dig into the resources files (colors_material.xml) and find the primary_dark_material_light resource you will see that it is set to #ff757575 and when you convert that from RGB to CMYK you get the value of 54% black, which lines up with the vague material guidelines documentation.

**Comment by Rainer-Lang** [comment]
@jonathanlmarsh Jist looked at http://www.google.com/design/spec/style/color.html ...
Section "Use alpha values for grey text, icons, and dividers"
And here Google writes: "To convey a hierarchy of information, you can use different shades for text. The standard alpha value for text on a white background is 87% (#000000). Secondary text, which is lower in the visual hierarchy, should have an alpha value of 54% (#000000). Text hints for users, like those in text fields and labels, have an even lower visual prominence and should have an alpha value of 26% (#000000)."

So for me it's obviously that this means that here is an alpha-value, not "only" grey.

How do you think?

**Comment by jonathanlmarsh** [comment]
@Rainer-Lang You know what, I am looking at the wrong color fields. The google implementation is using transparencies.

    <color name="primary_text_default_material_light">#de000000</color>
    <color name="secondary_text_default_material_light">#8a000000</color>

**Comment by rengwuxian** [comment]
Hi all,

2.1.3 has been released, with this fix.

You can check the [latest library version](https://github.com/rengwuxian/MaterialEditText#download) now.
