### ISSUE TITLE
Error layout for non focused EditText with min characters validation (2.0.3)

### ISSUE THREAD

**Issue by jczerski** [rengwuxian/MaterialEditText#151]
###### MaterialEditText library (version 2.0.3) 

When layout with MaterialEditTexts with min characters validation appears widgets are already validated, because their are empty. In version 1.8.3 of library the validation started after user focuses on the field.

I know it's connected with this commit: https://github.com/rengwuxian/MaterialEditText/commit/9c3d27c73f8f37ee73c71abd1bbaad319ac5f109

How to disable it right now and show default line color on begin?

Best regards,
Jack

**Comment by rengwuxian** [comment]
Good point. I'll try to introduce a good solution. Thanks.

**Comment by jczerski** [comment]
Thank You!

**Comment by rengwuxian** [comment]
Hi @jczerski ,

2.1.3 has been released. An attribute `checkCharactersCountAtBeginning` is added, and it determines whether to check the characters count at the first time the EditText is shown. Default value is true, so you have to set it to false to disable it.

You can check the [latest library version](https://github.com/rengwuxian/MaterialEditText#download) now.

**Comment by jczerski** [comment]
Hi @rengwuxian ,

it is a great news!
New attribute works great and it does what I expected.

Thank You one more time for fast improvement and wonderful library!

Cheers!

**Comment by TheFinestArtist** [comment]
WOW Very awesome!! :+1:
