### ISSUE TITLE
Cant change text color with style

### ISSUE THREAD

**Issue by danielgomezrico** [rengwuxian/MaterialEditText#152]
I apply this style... but the text appears as light gray
 <style name="AppTheme.EditText" parent="android:Widget.EditText">
    <item name="android:textColor">@android:color/black</item>
    <item name="android:textSize">15sp</item>
    <item name="met_baseColor">@android:color/darker_gray</item>
    <item name="met_floatingLabel">highlight</item>
    <item name="met_primaryColor">@color/green_accent</item>
    <item name="met_underlineColor">@android:color/darker_gray</item>
  </style>

Is there something wrong?

**Comment by rengwuxian** [comment]
Use` met_textColor` instead of `android:textColor`
