### ISSUE TITLE
"No resource identifier found for attribute"

### ISSUE THREAD

**Issue by HanderWei** [rengwuxian/MaterialEditText#153]
I try to add my package or the library path in the XML node, but it does't work.

**Comment by rengwuxian** [comment]
Are you trying to switch to v2.0 from v1.x? If so, you gotta add a prefix `met_` to every attribute. See more [here](https://github.com/rengwuxian/MaterialEditText/wiki).

**Comment by HanderWei** [comment]
I solve it. Because the "app" namespace conflicted.

I add 
        xmlns:app="http://schemas.android.com/apk/my package path"
in the MaterialEditText

**Comment by rengwuxian** [comment]
:+1:
