### ISSUE TITLE
Ellipsis and error possible bug

### ISSUE THREAD

**Issue by Kinnonii** [rengwuxian/MaterialEditText#170]
Hi, when using MaterialEditText with the singleLineEllipsis property as true, I get the following behavior, which I think it's a bug because of its 'unexpected' behavior.

If I validate the field when not in the beginning (the three points icon is visible) and I get an error, the error message is moved to the right of it. Cool, but if you navigate to the first letter the three points come invisible but the error text keeps to the right of the 'invisible' three points.

Also, validating a field and getting an error with that attribute as true, even if nothing is typed, the error message goes to the right.

I know this could be a desired behavior, but I don't know that. Finally, if you get an error with the three points visible, it remains as the primary color while the message and baseline are colored with the error color.

**Comment by rengwuxian** [comment]
Hi @Kinnonii ,

About the position issue, I've thought about it, and this is just the best solution I can think of. If you have some other good solution, let me know please. (I don't think animating the bottom text horizontally is a good idea, that's too eye-catching)

And about the color, I agree with you. I'll fix it.

**Comment by rengwuxian** [comment]
Hi @Kinnonii ,

2.1.3 has been released, with this fix.

You can check the [latest library version](https://github.com/rengwuxian/MaterialEditText#download) now.

**Comment by Kinnonii** [comment]
Great!
