### ISSUE TITLE
How to cancel error

### ISSUE THREAD

**Issue by alorma** [rengwuxian/MaterialEditText#177]
Hi.

After using `.setError()` is there any way to clear error dynamically? Without user input

**Comment by dawidhyzy** [comment]
+1

**Comment by rocboronat** [comment]
+1

@rengwuxian only for the information: @ganfra / MaterialSpinner hides the error with .setError(null), and I think it's a good approach :)

btw, thanks for your work!

**Comment by mmutuyu** [comment]
+1, need this feature

**Comment by Nomane** [comment]
+1

**Comment by leosk06** [comment]
`setError(null)` works now, so this should be closed.

**Comment by lipondevf** [comment]
setError(null) works fine, no more code manually
