### ISSUE TITLE
Clear button does not work whether the text is full

### ISSUE THREAD

**Issue by namhoang159** [rengwuxian/MaterialEditText#185]
Clear button works fine but there is a problem.
It does not work whether the text is fill out of edit text fully.
I tried to click on it but it always focus on the text, not the button.
Please check it.
Thank you!

**Comment by mvarnagiris** [comment]
https://github.com/rengwuxian/MaterialEditText/pull/183

**Comment by namhoang159** [comment]
Thanks @mvarnagiris
