### ISSUE TITLE
Not editable but clickable - possible?

### ISSUE THREAD

**Issue by Rainer-Lang** [rengwuxian/MaterialEditText#216]
I need an MaterialEditText where the input comes from a date picker - and I also want the delete-input-button of the MaterialEditText to reset the input.
So the user should be able to click on the text to open the date picker and should also be able to click on the reset-button.
Is this possible?

**Comment by Rainer-Lang** [comment]
Any suggestions?

**Comment by rocboronat** [comment]
Hi Rainer,

we're doing it nowadays. editable=false, focusable=true, clickable=true.

The issue is that the first time the user clicked the EditText, it get the focus, but it call the onClickListener() method.

**Comment by yacsrk** [comment]
Hey @Rainer-Lang.
I had to do a similar thing in one of my project. I managed to obtain what I want with a button and its style set to  "@style/Base.Widget.AppCompat.Spinner.Underlined"

        <Button
            android:id="@+id/button"
            style="@style/Base.Widget.AppCompat.Spinner.Underlined"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:focusable="true"
            android:focusableInTouchMode="true"
            android:paddingLeft="4dp"
            android:textSize="18sp" />

**Comment by Rainer-Lang** [comment]
@yacsrk Could you post an image?

**Comment by yacsrk** [comment]
![screen shot 2015-07-22 at 16 43 01](https://cloud.githubusercontent.com/assets/2781098/8828139/e287610a-3090-11e5-9e44-5e77cebbaf4f.png)

**Comment by Rainer-Lang** [comment]
Thanks.

My MaterialEdit looks same.
What I want is:
1) Click on text -> open DatePicker
2) click on the clear-btn (x) of the MaterialEdit -> empty MaterialEdit

**Comment by yacsrk** [comment]
1) Can be done by adding a simple onClickListener on the button
2) Add another button with a cross. When clicked, it clears the first button.

**Comment by Rainer-Lang** [comment]
I hoped that this can be done only with using MaterialEdit.
