### ISSUE TITLE
RTL problem in HelperText

### ISSUE THREAD

**Issue by mo0rti** [rengwuxian/MaterialEditText#258]
hi guys
i used this awesome MaterialEditText in RTL layouts but there is something strange.
when I fill "helperText" it appears on the left side.
any help would be appreciated.

**Comment by ibrahim132** [comment]
How i can use  RTL layouts with MaterialEditText ?

**Comment by mehdi7e** [comment]
add blow attribute in MaterialEditText   
 android:gravity="right"
