### ISSUE TITLE
Keyboard pops up immediately

### ISSUE THREAD

**Issue by Michaeldgeek** [rengwuxian/MaterialEditText#264]
I am using the library as shown below:
<com.rengwuxian.materialedittext.MaterialEditText
                android:id="@+id/login_password_input"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_marginTop="8dp"
                android:hint="Password"
                android:inputType="textPassword"
                android:singleLine="true"
                app:met_baseColor="@color/white"
                app:met_errorColor="@color/md_red_500"
                app:met_floatingLabel="highlight"
                app:met_iconLeft="@drawable/ic_visibility_off_black_24dp"
                app:met_primaryColor="@color/white"/>

But the keyboard pops up immediately the activity is ready. How do I stop that

**Comment by siavashabdoli** [comment]
@Michaeldgeek I want to have this problem :)) my textview is focused but keyboard is not appear.
