### ISSUE TITLE
Icon not showing

### ISSUE THREAD

**Issue by felipecastilhos** [rengwuxian/MaterialEditText#281]
Hi, i'm trying to add a left icon into the edittext, but it doesnt show. Any ideias?

        <LinearLayout
            android:id="@id/container"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:orientation="horizontal">
            <com.rengwuxian.materialedittext.MaterialEditText
                android:id="@+id/txt_cpf"
                android:layout_width="match_parent"
                android:layout_height="45dp"
                android:hint="@string/fragment_checker_cnd_cert_number"
                android:layout_weight="1"
                app:met_iconRight="@drawable/ic_menu_camera"
                />

                <FrameLayout
                    android:layout_width="wrap_content"
                    android:layout_height="match_parent"
                    android:layout_marginLeft="10dp"
                    android:layout_marginTop="10dp">
                    <Button
                        android:id="@+id/btn_clear"
                        android:background="#dad9d5"
                        android:drawableTop="@drawable/ic_close"
                        style="@style/search_button_edittext"
                        android:layout_centerVertical="true"
                        android:layout_gravity="center_vertical"
                        android:stateListAnimator="@null" />

                    <Button
                        android:id="@+id/btn_camera"
                        style="@style/search_button_edittext"
                        android:background="#dad9d5"
                        android:drawableTop="@drawable/ic_menu_camera"
                        android:stateListAnimator="@null"
                        android:layout_centerVertical="true"
                        android:layout_gravity="center_vertical"/>
                </FrameLayout>
        </LinearLayout>

**Comment by Anto1106** [comment]
<com.rengwuxian.materialedittext.MaterialEditText
            android:id="@+id/txt_cpf"
            android:layout_width="match_parent"
            android:layout_height="45dp"
            android:hint="@string/fragment_checker_cnd_cert_number"
            android:layout_weight="1"
            app:met_iconRight="@drawable/ic_menu_camera"
           app:met_iconPadding="0dp"
            />

**Comment by Anto1106** [comment]
I think by this it will work

**Comment by rk215** [comment]
i am able display left icon using below code.

<com.rengwuxian.materialedittext.MaterialEditText
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    **android:drawableLeft="@drawable/ic_edit_black"
    android:drawableStart="@drawable/ic_edit_black"**
    app:met_iconLeft="@drawable/ic_edit_black"/>

i forcefully need to add drawable left and start attribute to show left icon.
i hope this might help you.
