### ISSUE TITLE
How to change the floating label color without focus

### ISSUE THREAD

**Issue by felipecastilhos** [rengwuxian/MaterialEditText#324]
I'm trying to change the color of the floating label when it has no focus but its always light grey. I really need it to be black.

any ideias?

**Comment by tahir-mahmood-10p** [comment]
Any solution to this?
the color is fading too much

**Comment by felipecastilhos** [comment]
Nope, still waiting for a solution.

**Comment by ebrandes** [comment]
use this: **setFocusFraction(1f)** on code.
