### ISSUE TITLE
App compiled with Android Studio 3.0 crashes on Android < 8.0

### ISSUE THREAD

**Issue by svenjacobs** [rengwuxian/MaterialEditText#346]
We encounter the following problem since we've upgraded our project to Android Studio 3.0 (with the Android Gradle plugin 3.0.0):

```
Caused by: java.lang.RuntimeException: Font asset not found res/drawable-mdpi-v4/ic_clear_search_api_holo_dark.png
   at android.graphics.Typeface.createFromAsset(Typeface.java:304)
   at com.rengwuxian.materialedittext.MaterialAutoCompleteTextView.getCustomTypeface(MaterialAutoCompleteTextView.java:488)
   at com.rengwuxian.materialedittext.MaterialAutoCompleteTextView.init(MaterialAutoCompleteTextView.java:385)
   at com.rengwuxian.materialedittext.MaterialAutoCompleteTextView.<init>(MaterialAutoCompleteTextView.java:325)
     ... 40 more
```

It seems that `typedArray.getString(R.styleable.MaterialEditText_met_accentTypeface)` which is stored in `fontPathForAccent` suddenly resolves to some random drawable path in `MaterialAutoCompleteTextView` line [383](https://github.com/rengwuxian/MaterialEditText/blob/master/library/src/main/java/com/rengwuxian/materialedittext/MaterialAutoCompleteTextView.java#L383). However this **only** happens on devices with Android lower than 8.0.

Our styles have not been changed during the upgrade to AS 3.0:

```xml
<item name="met_typeface">fonts/UnitRoundedOT.otf</item>
<item name="met_accentTypeface">fonts/UnitRoundedOT.otf</item>
```

I have no idea what's going on here...

**Comment by svenjacobs** [comment]
Just changing a project to use Android Gradle plugin 3.0.0

```
classpath 'com.android.tools.build:gradle:3.0.0'
```

without changing anything else causes this problem.

**Comment by CaptMustache** [comment]
Same issue here... --push--

**Comment by svenjacobs** [comment]
Posted this issue on [StackOverflow](https://stackoverflow.com/questions/47075964/wrong-styleable-resource-value-resolved-for-app-compiled-with-android-studio-3-0).

**Comment by rengwuxian** [comment]
I've created a new project and tested MaterialEditText, and it worked fine. The floating label just showed up with the typeface I've set in `strings.xml`. I was using Android gradle plugin 3.0.0 (and gradle version 4.0 of course), and the test device was Samsung S8 (Android 7.0).

Is there something I miss during the test? Or could you give me a simple sample project that has this "Font asset not found" issue?

**Comment by svenjacobs** [comment]
> Is there something I miss during the test? Or could you give me a simple sample project that has this "Font asset not found" issue?

Luckily I can reproduce this with a [sample project](https://github.com/svenjacobs/met_issue_346). The problematic line seems to be

```xml
<item name="met_accentTypeface">fonts/trench100free.otf</item>
```

in `styles.xml`. When this line is commented out the app does not crash.

**Comment by svenjacobs** [comment]
Since I found this very strange I cloned your library and renamed the `met_accentTypeface` attribute to `met_typeface2` just for testing. With this naming of the attribute the app does **not** crash?! Please see branch [custom_aar](https://github.com/svenjacobs/met_issue_346/tree/custom_aar) of my sample project. 

So it seems to have something to do with the naming of the attribute and a possible bug of the Android Gradle plugin?

**Comment by svenjacobs** [comment]
Again, when I rename the attribute to `met_abcTest` for example the app crashes.

Also when I apply the attribute directly to the view via `app:met_accentTypeface="fonts/trench100free.otf"` instead of `styles.xml` the app **does not** crash.

**Comment by rengwuxian** [comment]
Got it.

I got to reproduce this issue, and figured it out, Partially. I only found the solution, but not the reason.

I tried putting the path string of the font `font/xxx.xxx` into `strings.xml` as a string item (with a name `fontpath` for example) and using `@string/fontpath` instead of the very path string directly. And then it worked. The crash just disappeared. It seems like the compiler won't take the value in `<style> -> <item>` tag as a string, but the `@string/` form will work.

**So the solution: Don't use the file path of the font directly. Put the font path into `strings.xml`, and use the string definition `@string/` instead.**

But, just as I said, I've not found the reason. I don't know why the direct file path doesn't work.

I hope this is enough for you?

**Comment by svenjacobs** [comment]
@rengwuxian Thanks for your investigation. Putting the font path into a string resource seems to be an acceptable workaround. However I find it very strange that the issue disappears when for example the attribute is renamed. This random behaviour of the compiler / plugin **plus** the fact that it only started occurring with AS 3.0 and yet only for Android < 8.0 probably points to a bug of the plugin which should be addressed by Google.

**Comment by rengwuxian** [comment]
Yes, as far as the facts we've seen show, it looks like a bug of AS 3.0 / Android gradle plugin 3.0 / gradle 4.0.

Or... it's Google's decision, to make the naming rule more strict?

**Comment by rengwuxian** [comment]
Shall I close the issue?

**Comment by svenjacobs** [comment]
> Or... it's Google's decision, to make the naming rule more strict?

I doubt it. I would assume a compilation error if this would be the case and not a random behaviour of the plugin which results in crashes.

> Shall I close the issue?

Closed it with this comment.

**Comment by rengwuxian** [comment]
> I doubt it. I would assume a compilation error if this would be the case and not a random behaviour of the plugin which results in crashes.

That makes sense.

**Comment by raitucarp** [comment]
I confirm this, it's crash again when android build gradle version is 3.1.0
