### ISSUE TITLE
Add icons.

### ISSUE THREAD

**Issue by Wolftein** [rengwuxian/MaterialEditText#42]
Add icons using drawableLeft, drawableRight just like
http://material-design.storage.googleapis.com/publish/v_2/material_ext_publish/0Bx4BSt6jniD7MzFBNE9JWTk5ZHc/components_textfields_single9.png

**Comment by hzsweers** [comment]
@guyzk I think that sort of implementation should be left to the developer, maybe pull request a sample that @rengwuxian could include in the sample APK?

**Comment by rengwuxian** [comment]
@hzsweers 

If the developer wants to just add an static icon, there's no need to provide a support, like what you said. But it'll be a complex job to leave this to developers, if they just want to implement the same appearance as what Google's design guide shows, like this:

![text_field_with_icon](http://material-design.storage.googleapis.com/publish/v_2/material_ext_publish/0Bx4BSt6jniD7S2NCRjNkZk9SVkU/components_textfields_single7.png)

What @guyzk needs is the dynamically icon rendering and color switching feature. Or maybe I misunderstood what you mean, let me know please.

This feature will come in the next version, in about 1 or 2 days.

**Comment by guyzk** [comment]
That's exactly what i meant. A inner compound drawable that changes colors by state (empty field, filled field, field in error state).
I think this would be a great addition to the already great library. Great work!!

**Comment by rengwuxian** [comment]
@Wolftein @guyzk 

1.8.0 has been released, with this new feature.

![material design icon](https://raw.githubusercontent.com/rengwuxian/MaterialEditText/master/images/material_design_icon.png)

You can check the [latest library version](https://github.com/rengwuxian/MaterialEditText#download) now. 

_It may take several hours syncing to Maven Central._

**Comment by Wolftein** [comment]
Amazing work :)

**Comment by guyzk** [comment]
Great! I'll be sure to check it out soon

**Comment by sharanangadi** [comment]
materialEditText.setHint(getString(hintStr[i]));

setting hint dynamically wont work
