### ISSUE TITLE
font size problem

### ISSUE THREAD

**Issue by recoverrelax** [rengwuxian/MaterialEditText#45]
Hey. Is it possible to have two diferent font sizes for the value and the hint? I can change the value font size but the hint is too small sometimes, and i find no information in the wiki on how to change only the hint font sixr. Is there any option?

**Comment by recoverrelax** [comment]
1.7.1 is out. is this functionality active yet? can't find it in the docs

**Comment by rengwuxian** [comment]
Not yet. I made some mistake in v1.7.0, and v1.7.1 become the bug fix version for v1.7.0. v1.8.0 is coming, with this functionality, tomorrow.

**Comment by rengwuxian** [comment]
@recoverrelax 

1.8.0 has been released. Floating label and bottom texts' text sizes are able to be customized now (with `setXXXTextSize()`).

You can check the [latest library version](https://github.com/rengwuxian/MaterialEditText#download) now. 

_It may take several hours syncing to Maven Central._

**Comment by recoverrelax** [comment]
Yo. Thanks for your effort friend. Altought i can't find it. There is indeed a function called that, something like this: editText.setTextSize() and none of, for example, editText.setFloatingLabelTextSize() as you suggesed. Can you give me a clear example how to change the floating label text size please?

**Comment by rengwuxian** [comment]
I forgot it. I'll add that at the next version, in about 2 days. Thanks!

**Comment by rengwuxian** [comment]
@recoverrelax 

1.8.1 has been released, with programmatic setter of floating label and bottom texts's text size.

You can check the [latest library version](https://github.com/rengwuxian/MaterialEditText#download) now. 

_It may take several hours syncing to Maven Central._

**Comment by recoverrelax** [comment]
i have checked and its awesome, thank your for your effort. I havea another question, at the moment, im using this lybrary and the error text is shown at the bottom of the view, red and left-centered. is it possible to center at the middle?

**Comment by rengwuxian** [comment]
@recoverrelax That makes sense. I'll make the helper/error text also affected by `gravity` at the version, and I'll let you know then.. Thanks for your feedback.

**Comment by rengwuxian** [comment]
@recoverrelax 

1.8.2 has been released. Bottom texts can be influence by `android:gravity` now.

You can check the [latest library version](https://github.com/rengwuxian/MaterialEditText#download) now. 

_It may take several hours syncing to Maven Central._
