### ISSUE TITLE
RTL Support

### ISSUE THREAD

**Issue by hzsweers** [rengwuxian/MaterialEditText#47]
Have you looked into RTL support much? The EditText field itself supports it, but the accent texts still draw from left to right when it's enabled

**Comment by rengwuxian** [comment]
@hzsweers 

1.8.0 has been released, with RTL support (experimental). I know little about RTL languages, so I'm not sure if there's something not proper.

You can check the [latest library version](https://github.com/rengwuxian/MaterialEditText#download) now. 

_It may take several hours syncing to Maven Central._

**Comment by hzsweers** [comment]
Awesome! I'll check it out and report any bugs I find. Flipboard supports
RTL languages, so you'll be working with them more soon enough :)
