### ISSUE TITLE
Predraw wrong height

### ISSUE THREAD

**Issue by nekdenis** [rengwuxian/MaterialEditText#52]
If "helperText" param specified there are small issue. At first rendering pass (https://developer.android.com/guide/topics/ui/how-android-draws.html) edittext draws with large height. And only after second pass gets normal. 
So when I open my activity my edittexts jumping at first second. The first time they have huge bottom padding and then they get normal.

**Comment by rengwuxian** [comment]
Sorry for the late reply. I missed this issue. I'll check it.

**Comment by rengwuxian** [comment]
Didn't see this problem. Could you provide more details to help me find that?

**Comment by rengwuxian** [comment]
Closing for no responce
