### ISSUE TITLE
Can't add this Library ?

### ISSUE THREAD

**Issue by AruLNadhaN** [rengwuxian/MaterialEditText#54]
I Tried to Add this library. But it gives a UNEXPECTED TOP-LEVEL EXCEPTION.

See this link for Details 
 http://stackoverflow.com/questions/27719436/how-to-remove-duplicate-libraries-added-via-gradle

**Comment by extraRam** [comment]
I think we had the same issue, something like ```app:dexdebug``` exception. What I did is this:

```
compile ('com.rengwuxian.materialedittext:library:1.7.1') {
        exclude group: 'com.nineoldandroids', module: 'library'
    }
```

and it worked for me.

**Comment by AruLNadhaN** [comment]
Yeah it solved the Problem!
