### ISSUE TITLE
Set focusable, focusableInTouchMode and clickable attributes to false in XML

### ISSUE THREAD

**Issue by lavarewindkiosk** [rengwuxian/MaterialEditText#55]
This is related to closed issue #44.

I'd like to set the focusable, focusableInTouchMode and clickable attributes to false in XML.

Unfortunately, I can't do so as the MaterialEditText constructor forces these to true after calling super.

Could these be removed or worked around somehow in order to provide the ability to set these properties in XML?

**Comment by rengwuxian** [comment]
OK, I'll fix it at next version. Thanks for your feekback.

**Comment by rengwuxian** [comment]
@lavarewindkiosk 

1.8.1 has been released, with a bug fix of this.

You can check the [latest library version](https://github.com/rengwuxian/MaterialEditText#download) now. 

_It may take several hours syncing to Maven Central._
