### ISSUE TITLE
Option to disable transition animations

### ISSUE THREAD

**Issue by lavarewindkiosk** [rengwuxian/MaterialEditText#56]
I love the way that the floating label animates into view, but I don't always want this in my application.

Is it possible to add a setting and styleable to enable/disable this feature? Default on would be ok.

**Comment by rengwuxian** [comment]
Good idea. plan to add the custom animation support, and `null` should means no animation. Thanks.

**Comment by rengwuxian** [comment]
@lavarewindkiosk 

1.8.2 has been released. Set `app:floatingLabelAlwaysShown` will keep the floating label at the top. In addition, I found it's not what we need to provide custom transition animations, so I didn't add the custom animation support.

You can check the [latest library version](https://github.com/rengwuxian/MaterialEditText#download) now. 

_It may take several hours syncing to Maven Central._

**Comment by JKMirko** [comment]
@rengwuxian

Is it possible to temporarily disable floating label animation?
On one screen I set text to some input fields programmatically and in this case I would like to disable animation. Is this possible?
