### ISSUE TITLE
Hide Underline changes the size of the view

### ISSUE THREAD

**Issue by lavarewindkiosk** [rengwuxian/MaterialEditText#57]
When modifying the hideUnderline property, the size of the view changes according to whether the underline is shown or not.

This is not ideal if the underline is being toggled programmatically, as it may affect the positioning of the text itself (if layout_gravity is anything other than top) or it may affect the placement of any views below it.

I think that hideUnderline should preserve the space where the underline should go, similarly to the way that View.INVISIBLE works as opposed to View.GONE within layouts.

Perhaps the View.INVISIBLE and View.GONE values could be used in order to support both variants.

**Comment by hzsweers** [comment]
I thought about this, but in testing having an invisible underline meant there was an odd looking extra space beneath the underline. What use case would you want to hide the underline and enable it again that couldn't be done with just setting one of the colors to be transparent?

**Comment by lavarewindkiosk** [comment]
I'm developing a form displays some information. There is a button which toggles the editable state of the information, and the presence of the underline would indicate each field which is editable. I don't want the text jumping around when pressing the button.

I could achieve this through other means, but the cleanest way to do this would be through an explicit setting in the MaterialEditText itself.

I hadn't thought of using colours -- in the docs it doesn't appear that there is a colour setting which affects only the underline colour, but I will check again. In the documented example, the underline colour seems to be set using the errorColor property, I could use this as a clever workaround but would much prefer not to. 

Really impressed with this widget in general, by the way, it's the best of the few that I've tried.

**Comment by rengwuxian** [comment]
Why not use `setEnabled()` method? Hiding underline is just a style option,
not for a specific state, like disabled.
2015年1月6日 下午5:28于 "lavarewindkiosk" <notifications@github.com>写道：

**Comment by lavarewindkiosk** [comment]
setEnabled(false) has unwanted side effects.
- changes the colour of the text to grey
- displays an underline in a dotted form

In my specific use case, I require that:
- the text remains black
- the underline is hidden
- the vertical height of the control and positioning of the floating label is the same

**Comment by rengwuxian** [comment]
Got it. But it looks like a uncommon use case, so you'd better solve it yourself, using some workaround. ^_^

**Comment by angelen10** [comment]
Well, I have some problems to ask.How to change the height of underline when the EditText is focused and is not focused?

**Comment by rengwuxian** [comment]
MaterialEditText's underline's height is the same as Lollipop's EditText's
(1d at non-active state and 2dp at active state). It's fixed.
2015年1月10日 上午12:26于 "俨小良" <notifications@github.com>写道：

**Comment by angelen10** [comment]
@rengwuxian Thank you, I got it.

**Comment by lavarewindkiosk** [comment]
Thanks for looking into this for me.

I will work around it, but I still feel that the principle of my suggestion is warranted -- at least once the widget has been initialised, showing / hiding any parts should not unduly change the height of the control.

**Comment by Rainer-Lang** [comment]
@lavarewindkiosk I have the same "problems" like you - and I completely agree with you. Do you have a workaround yet?

**Comment by lavarewindkiosk** [comment]
In the end, I used a different UI model which didnt require this feature.

Google have recently released their Design Support Library which provides a
Material Edit Text implementation:
http://android-developers.blogspot.co.uk/2015/05/android-design-support-library.html
