### ISSUE TITLE
Support for background attribute

### ISSUE THREAD

**Issue by hzsweers** [rengwuxian/MaterialEditText#58]
Title kind of says it. It would be useful to be able to set a background color/resource/drawable, right now it seems the library just ignores these attributes (both in xml and programmatically). Particularly because sometimes you want to use a special 9-patch for the background

**Comment by rengwuxian** [comment]
Is this really useful? I've thought about this, and there're 2 reasons I didn't support this attribute:

1. I don't think when developers use MaterialEditText, they'd like to set a custom background.
2. If they really do, I'm not sure how to put the background image. I mean, should the floating label be in or out of the background? And what about the bottom texts?

**Comment by hzsweers** [comment]
Hmm, that is true. The 9patch is the best reason I can think of, but you're
right in that it might be easier for developers to just use a regular
EditText for that
