### ISSUE TITLE
Add support for MultiAutoCompleteTextView

### ISSUE THREAD

**Issue by maxpower47** [rengwuxian/MaterialEditText#59]
Add support for the MultiAutoCompleteTextView subclass of AutoCompleteTextView.

http://developer.android.com/reference/android/widget/MultiAutoCompleteTextView.html

**Comment by rengwuxian** [comment]
@maxpower47  1.8.0 has been released, with the new class `MaterialMultiAutoCompleteTextView`.

You can check the [latest library version](https://github.com/rengwuxian/MaterialEditText#download) now. 

_It may take several hours syncing to Maven Central._
