### ISSUE TITLE
Problem with Focus

### ISSUE THREAD

**Issue by LeMimit** [rengwuxian/MaterialEditText#61]
Hello,

When you have a MaterialEditText in one activity, this MaterialEditText gets focus when this activity starts and then the keyboard appears. How can I clear this focus to let the user decide if he wants to edit this field or not by clicking on it.

TLDR : How remove the autofocus of MaterialEditText ?

Thanks !

Have a nice day.

**Comment by rengwuxian** [comment]
Hi, LeMimit. This is a problem with a long history. Try Google "Android EditText remove auto focus", and you'll get the answer.^_^

**Comment by LeMimit** [comment]
Thanks !! 

I found my happiness

Have a nice day.
