### ISSUE TITLE
Add programmatic setter access to icons

### ISSUE THREAD

**Issue by freezy** [rengwuxian/MaterialEditText#63]
Icons can only be set in the XML view and imply that there's an actual bitmap resource.

I'm using the excellent [android-material-icons](https://github.com/Malinskiy/android-material-icons) library, which generates the bitmaps from a vector font, allowing indefinite, crisp resizing and avoids having to generate 5 images for every icon.

Programmatically, I can pull out a `Drawable` in any size and color, but I can't seem to apply it on `MaterialEditText`. A setter would be very much appreciated.

**Comment by rengwuxian** [comment]
OK. I'll comment at this issue when I add this support.

**Comment by freezy** [comment]
Thanks! Let me know when you start working on it, I might come up with a PR
before.

**Comment by rengwuxian** [comment]
Haha! I'll appreciate if you could help me with it. I just planned to add this in 1 or 2 days when I saw this issue.

**Comment by freezy** [comment]
You might beat me to it then. ;)

**Comment by rengwuxian** [comment]
@freezy 

1.8.1 has been released, with this new functionality.

You can check the [latest library version](https://github.com/rengwuxian/MaterialEditText#download) now. 

_It may take several hours syncing to Maven Central._

**Comment by freezy** [comment]
That was fast, cheers!

I'll test and close tomorrow.

**Comment by freezy** [comment]
Works like a charm. Thanks!
