### ISSUE TITLE
1.8 makes all text white, regardless of what they're set in XML

### ISSUE THREAD

**Issue by hzsweers** [rengwuxian/MaterialEditText#64]
No idea why or where this comes from, but yeah. Hint and text colors are both white now, and changing it in XML doesn't fix it either. Has anyone else run into this?

**Comment by rengwuxian** [comment]
No, no one else. And I had run the sample code before 1.8.0 was released and found nothing wrong. Now it sounds like I missed something. I'll check it tomorrow.

**Comment by hzsweers** [comment]
Alright, I'll try to write up a snippet that exhibits this later

**Comment by hzsweers** [comment]
Aaaaand of course now I can't reproduce this myself ಠ_ಠ. Sorry about this.

**Comment by hzsweers** [comment]
Found the issue. I had a rogue `textColorPrimary=@color/white` set in styles somewhere, so it was my problem :P

**Comment by rengwuxian** [comment]
Aha. Whatever, it's good to have indicated the problem.
2015年1月12日 下午3:25于 "Henri Sweers" <notifications@github.com>写道：
