### ISSUE TITLE
XML Layout background attr is ignored

### ISSUE THREAD

**Issue by jbruchanov** [rengwuxian/MaterialEditText#66]
If you specify view in xml file and specify custom background, it's completely ignored.
```xml
<com.rengwuxian.materialedittext.MaterialEditText
            .....
            android:background="#F00" />
```
https://github.com/rengwuxian/MaterialEditText/blob/master/library/src/main/java/com/rengwuxian/materialedittext/MaterialEditText.java#L349

**Comment by rengwuxian** [comment]
Yes, it's ignored. Developers could use baseColor and primaryColor to set the underline's background, what help developers implement Material Design easily.
