### ISSUE TITLE
Normal underline color is black with 12% alpha

### ISSUE THREAD

**Issue by yanzm** [rengwuxian/MaterialEditText#67]
In Sticker sheet, the normal underline color is black with 12% alpha.
http://www.google.com/design/spec/resources/sticker-sheets-icons.html#sticker-sheets-icons-components
This color is same as divider http://www.google.com/design/spec/components/dividers.html#dividers-specs

(disabled dotted line is black with 26% alpha. )

**Comment by rengwuxian** [comment]
1.8.2 has been released, with this fixed. Thanks, @yanzm , you're so careful.

You can check the [latest library version](https://github.com/rengwuxian/MaterialEditText#download) now. 

_It may take several hours syncing to Maven Central._
