### ISSUE TITLE
Floating label cannot be enabled after construction

### ISSUE THREAD

**Issue by danhawkes** [rengwuxian/MaterialEditText#71]
If you're creating the view programmatically, e.g.

```java
MaterialEditText t = new MaterialEditText(context);
t.setFloatingLabel(2);
```
…the floating label does not work because its text-changed and focus-changed listeners are only ever registered in the constructor. 

Think it's necessary to configure these as a result of calling the public setter, and set up initial state by calling the setter with `setFloatingLable(<the default state>) from within the constructor.

**Comment by rengwuxian** [comment]
@danhawkes 

1.8.2 has been released, with this fixed.

You can check the [latest library version](https://github.com/rengwuxian/MaterialEditText#download) now. 

_It may take several hours syncing to Maven Central._
