### ISSUE TITLE
EditText without FloatingLabel but with (static, non-floating) Label possible?

### ISSUE THREAD

**Issue by Rainer-Lang** [rengwuxian/MaterialEditText#72]

**Comment by rengwuxian** [comment]
Same problem with #62

**Comment by rengwuxian** [comment]
@Rainer-Lang 

1.8.2 has been released. Set `app:floatingLabelAlwaysShown` will keep the floating label at the top. 

You can check the [latest library version](https://github.com/rengwuxian/MaterialEditText#download) now. 

_It may take several hours syncing to Maven Central._
