### ISSUE TITLE
Multiline doesn't work

### ISSUE THREAD

**Issue by Aracem** [rengwuxian/MaterialEditText#73]
Hello, thanks for the awesome library

I have a problem with an MaterialEditText that has to be Multiline. 
I set this xml attributes:

...
 android:layout_height="wrap_content"
 android:lines="2"
 android:minLines="2"
 android:maxLines="4"
 android:inputType="text|textMultiLine|textCapSentences"
...

But it not show a multiline edit text.
Does MaterialEditText have support for multiline edit text?

**Comment by pawelantczak** [comment]
Try this [link](http://stackoverflow.com/a/4233683/214081).

**Comment by Aracem** [comment]
Thanks @pawelantczak but how I put I have setted all the fields. The problems seems that MaterialEditText override that fields to not let the edittext be multiline

**Comment by Aracem** [comment]
I resolve the problem. I have configured the app:singleLineEllipsis="true" attribute that set singleLine option in the initialization.

This issue could be closed

**Comment by ibrahim132** [comment]
I have the same problem how i can fix it ? Please help!
