### ISSUE TITLE
Unwanted bottom padding in version 1.8.1

### ISSUE THREAD

**Issue by glodos** [rengwuxian/MaterialEditText#77]
Hi,

Today I updated to version 1.8.1 and all instances of the widget have additional bottom padding. Here are images for comparison:
v 1.8.1:
![device-2015-01-16-001015](https://cloud.githubusercontent.com/assets/2659001/5768896/7675ed38-9d15-11e4-9a02-7029e70898a0.png)
v1.7.1
![device-2015-01-16-001731](https://cloud.githubusercontent.com/assets/2659001/5768898/7adbbfc4-9d15-11e4-8a9f-bfb12b58f86d.png)

Thanks in advance for fixing this.

**Comment by rengwuxian** [comment]
@glodos 

1.8.2 has been released, with "unexpected padding" bug fixed.

You can check the [latest library version](https://github.com/rengwuxian/MaterialEditText#download) now. 

_It may take several hours syncing to Maven Central._

**Comment by glodos** [comment]
Big thanks!
