### ISSUE TITLE
error: No resource identifier found for attribute 'iconDrawable' in my package

### ISSUE THREAD

**Issue by S-Masoud-Emamian** [rengwuxian/MaterialEditText#81]
hi
I would like to use ButtonFloatSmall view, but when I add it  I get an error : 

      error: No resource identifier found for attribute 'iconDrawable' in my package

		        <com.gc.materialdesign.views.ButtonFloatSmall
		            android:id="@+id/buttonColorSelector"
		            android:layout_width="wrap_content"
		            android:layout_height="wrap_content"
		            android:layout_marginLeft="32dp"
		            android:layout_marginTop="108dp"
		            android:background="#1E88E5"
		            materialdesign:iconDrawable="@drawable/icn_select_color"  />

-----------
parent layout : 

     <ScrollView xmlns:android="http://schemas.android.com/apk/res/android"
            xmlns:custom="http://schemas.android.com/apk/res-auto"
            xmlns:app="http://schemas.android.com/apk/res/mypackage"
            xmlns:materialdesign="http://schemas.android.com/apk/res-auto"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:scrollbars="none" >

I am using eclipse .

**Comment by rengwuxian** [comment]
Looks like you got the wrong library. It's MaterialEditText here.
