### ISSUE TITLE
icon isn't at the keyline: left 16dp

### ISSUE THREAD

**Issue by Rainer-Lang** [rengwuxian/MaterialEditText#85]

**Comment by rengwuxian** [comment]
Hi, @Rainer-Lang . 

Thanks! I'll take some time on the new spec, and try to make MaterialEditText better.

**Comment by Rainer-Lang** [comment]
Thanks a lot.
If I can assist you - please write me. :-)

**Comment by rengwuxian** [comment]
Hi @Rainer-Lang ,

2.0.3 has been released, with this fixed.

You can check the [latest library version](https://github.com/rengwuxian/MaterialEditText#download) now.
