### ISSUE TITLE
setText not working as expected

### ISSUE THREAD

**Issue by savaskoc** [rengwuxian/MaterialEditText#86]
I think [video](http://www.youtube.com/watch?v=O3bf2G5QZGo&feature=youtu.be) is describing the problem enough.

I'm sure that setText function called once. And when I call getText function, I get it's text correctly but not shown in view looks like video

**Comment by rengwuxian** [comment]
Hi, @savaskoc .

That looks weird. But it looks hard to reproduce. Could you share me a sample project?

**Comment by savaskoc** [comment]
That looks really weird... When i'm using setText in onViewCreated my text
disappear. But when i use setText in "new Handler().post" it looks good. I
think input's text cleared in somewhere after onViewCreated
31 Oca 2015 18:44 tarihinde "Kai Zhu" <notifications@github.com> yazdı:

**Comment by rengwuxian** [comment]
Have you find the issue? Or you can send me a simplified demo project so I can reproduce it and try to find out the problem.
