### ISSUE TITLE
Inconsistent font between MaterialEditText and MaterialAutoCompleteTextView

### ISSUE THREAD

**Issue by Wolftein** [rengwuxian/MaterialEditText#87]
Both widget are using the same font size, but won't look the same.

![issue](https://cloud.githubusercontent.com/assets/1273705/5829252/140e302e-a0ee-11e4-85de-377a550a40f8.png)

Top widget is MaterialAutoCompleteTextView and the other is MaterialEditText

**Comment by rengwuxian** [comment]
Hi, @Wolftein .

Thanks for your feedback. Have you tried to replace the MaterialXXX widgets with the builtin widgets and see if this situation stay the same? Sorry for the late reply.

**Comment by Wolftein** [comment]
Yes, found out it was due to Cyanogen Mod font's system, thanks :).
