### ISSUE TITLE
OnFocusChangeListener not working if Floating Label is set to "normal"

### ISSUE THREAD

**Issue by traninho** [rengwuxian/MaterialEditText#88]
Hi,

I was trying to set OnFocusChangeListener to MaterialEditText view and I was wondering why OnFocusChanged() has never been called. So I reviewed your code and I found out where the issue is:

```
...
innerFocusChangeListener = new OnFocusChangeListener() {
      @Override
      public void onFocusChange(View v, boolean hasFocus) {
        if (floatingLabelEnabled && highlightFloatingLabel) {
          if (hasFocus) {
            if (getLabelFocusAnimator().isStarted()) {
              getLabelFocusAnimator().reverse();
            } else {
              getLabelFocusAnimator().start();
            }
          } else {
            getLabelFocusAnimator().reverse();
          }
          if (outerFocusChangeListener != null) {
            outerFocusChangeListener.onFocusChange(v, hasFocus);
          }
        }
      }
    };
super.setOnFocusChangeListener(innerFocusChangeListener);
```

The problem is that this block of code will not pass the first if statement so the outerFocusChangeListener is never called.

**Comment by danielgomezrico** [comment]
Same thing for me

**Comment by yavor-tvx** [comment]
As a temporary solution subclass MaterialEditText and override setOnFocusChangeListner() by setting an internal focus change listener. Then from your client call setOnFocusChangeListener() and make sure that in the internal listener you call through super(). Once that gets resolved removed the subclass as you would generate StackOverflowException.

**Comment by gcmorrison** [comment]
It looks like this bug is already fixed, but it hasn't been released yet.  The bug also happens when you're  running the floatLabel on anything other than "highlight" mode.  So, while we patiently wait for the official fix to be released, an easy workaround for now is to just set the floating label to highlighted.
i.e. app:floatingLabel="highlight"

**Comment by rengwuxian** [comment]
Hi all,

1.8.3 has been released. This is fixed.

You can check the [latest library version](https://github.com/rengwuxian/MaterialEditText#download) now. 

_It may take several hours syncing to Maven Central._
