### ISSUE TITLE
在fragment中使用的时候，settext("str")无效

### ISSUE THREAD

**Issue by xiaohong001** [rengwuxian/MaterialEditText#91]
我的EditFragment在列表界面
当第一次replace的时候，pwd的值是初始的值，比如abc
在onCreateView
pwd=  getArguments().getString(PWDKEY);
edTitle.setText(pwd);
此时pwd得到的值是abc，edTitle显示的值也是abc

当我操作完成后remove掉，编辑另外一个，继续replace的时候
pwd获取的值是123，然后edTitle的值还是abc

多次试验，pwd的值每次不一样，但edTitle的值始终都不变

**Comment by rengwuxian** [comment]
你好， @xiaohong001 

MaterialEditText没有对EditText的基本功能做修改。能否请你在EditText上试一下看看这个情况是否依然存在？
最近在忙一些事情，抱歉回复比较慢！

**Comment by xiaohong001** [comment]
普通的edittext是可以显示的，现在我加了个
new Handler().post(new Runnable() {
            @Override
            public void run() {
                edTitle.setText(str);
            }
        });
就可以正常显示了

**Comment by rengwuxian** [comment]
Hi, @xiaohong001 ,
这个问题解决了吗？
我写了测试工程分别在EditText和MaterialEditText上测试，replace掉Fragment之后在onCreateView()中写入的text都是可以在新的Fragmnet中被显示的（我没有用Handler之类的workaround）。目前我无法定位到你的问题。如果有需要解决的话，你可以发我一份简化的工程，我好在本地查看你的问题。谢谢反馈！
