### ISSUE TITLE
Contents are not saved after screen orientation changed

### ISSUE THREAD

**Issue by SukharevAndrey** [rengwuxian/MaterialEditText#92]
All entered text in fields disappears after screen orientation change. Yes, I know that it could be saved manually, but builtin EditText does it automatically.
These errors are generated many times after orientation change:
```
E/ViewRootImpl﹕ sendUserActionEvent() mView == null
...
E/SpannableStringBuilder﹕ SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
```

Tested on Genymotion w/ Android 5.0, Samsung Galaxy S4 w/ Android 4.2.2, Lenovo w/ Android 4.4.2.

**Comment by rengwuxian** [comment]
Hi, @SukharevAndrey .

Yes, an EditText without auto-save support sucks.
But MaterialEditText does nothing to the text area, so this bug sounds strange. Have you tried replace the MaterialEditText to see if it still appears? If so, Could you please upload a demo apk file?

**Comment by SukharevAndrey** [comment]
@rengwuxian 
Content saving doesn't work even in your sample apk! Just try to delete default text (for example in header), write your own and then rotate device. The text will not be saved and will be restored to default text. The only field in sample apk that does text saving is switchable one.

**Comment by rengwuxian** [comment]
That's expected. Android automatically saves and restores widgets' states by using the `id` attribute. A widget's state cannot be saved without an `id`. The "Basic" EditText in my sample module has an id, which is used to set its enable state when clicking the "disable/enable" button. So its text can be saved and restored. And it's not the ONLY one -- there're 4 EditText having `id` in the sample.
