### ISSUE TITLE
add a clear button？

### ISSUE THREAD

**Issue by sd6352051** [rengwuxian/MaterialEditText#93]
hi

I use yout lib in my project.really great.I hope  have a clear button.
Can you add this feature?

Thanks

**Comment by Rainer-Lang** [comment]
+1

**Comment by rengwuxian** [comment]
Looks great. I'll add this feature, but I'm afraid that won't be soon. I've been busy on some other work these days, and I'll add this feature after that.

**Comment by sd6352051** [comment]
hi,
Can you call me when add this feature?
:smile:

**Comment by rengwuxian** [comment]
Sure I will.

**Comment by Arkezis** [comment]
+1 =)

**Comment by Rainer-Lang** [comment]
Maybe it's also possible to add an icon with an OnClickListener.

**Comment by rengwuxian** [comment]
Hi all,

2.0.3 has been released, and clear button is added.

You can check the [latest library version](https://github.com/rengwuxian/MaterialEditText#download) now.

**Comment by sd6352051** [comment]
It's working like charm man ;) :+1:
