### ISSUE TITLE
Add ability to specify custom hint/edittext colors

### ISSUE THREAD

**Issue by athornz** [rengwuxian/MaterialEditText#94]
MaterialEditText currently takes the base color and modifies its opacity. This is good for a default implementation, but in some cases we need the ability to override all colours ourselves.

Having attributes for the hint, underline, floating label color etc would be great (These would override the base color/primary color etc).

**Comment by csbenz** [comment]
Need this too, would be awesome :)

**Comment by lenant** [comment]
Totally support this one, sometimes you really need the darker version, and current underline and hint are too light. I would truly love the ability to set precise colors.

**Comment by chriswiesner** [comment]
same here!

**Comment by rengwuxian** [comment]
Hi all,

Sorry for the delayed reply. `MaterialEditText` 2.0 is gonna be released in about 2 weeks, with a lot of customization options, including texts' colors. It's not that hard to implement these features, but I have some other work to deal with, so I have really little time on this library. That why it'll take 2 more weeks.

**Comment by Aracem** [comment]
Thank you so much @rengwuxian for your work :)

**Comment by elwoodxblues** [comment]
+1

**Comment by petersnoopy** [comment]
Same here, it would be a great feature to be able to change the opacity.

**Comment by rengwuxian** [comment]
Hi all,

2.0.3 has been released, introducing this feature. You just use `met_textColor` and `met_textColorHint`.

You can check the [latest library version](https://github.com/rengwuxian/MaterialEditText#download) now.

**Comment by athornz** [comment]
Thanks so much! Such a great library :)

**Comment by petersnoopy** [comment]
Nice!!!

**Comment by Aracem** [comment]
:+1:  :clap:
