### ISSUE TITLE
How can I use it with rtl

### ISSUE THREAD

**Issue by chaimleu** [rengwuxian/MaterialEditText#97]
I need that the highlight will be in the right side and not in the left side?
this is possible?
Thanks!

**Comment by rengwuxian** [comment]
If you want rtl, just enable the `supportsRtl` attribute in the manifest file, and set `android:textDirection="rtl"`, then everything goes automatic.

**Comment by hkelidari** [comment]
floating label direction change correctly but error text direction change to ltr! by my review this problem not exist by ltr Language. this problem occur by rtl Language.  in rtl Language, direction error text is rtl by default when change direction by android:textDirection="rtl", direction change to ltr not rtl!
