### ISSUE TITLE
Add style options to documentation

### ISSUE THREAD

**Issue by burgerga** [rengwuxian/MaterialEditText#99]
I want most of my MaterialEditTexts in one style so I added the following definition in `styles.xml`.

    <style name="MyMaterialEditTextStyle" parent="android:Widget.EditText">
        <item name="primaryColor">@color/accent</item>
        <item name="floatingLabel">highlight</item>
        <item name="errorColor">@color/error_red</item>
    </style>

It works, but is this the way you're supposed to do it? (for example taking Widget.EditText as parent?)

**Comment by rengwuxian** [comment]
Hi @burgerga ,

Sorry for the delayed reply. As you said, it's boring to set style for every MaterialEditText. Do you have some good suggestion to provide an elegant way? MaterialEditText hasn't implement a theme, and AFAIK, there's no way to provide a uniform default style for a widget witch has no style options in the theme's attrs.xml(or someOther.xml) file.

Thanks!

**Comment by VladSumtsov** [comment]
https://github.com/afollestad/material-dialogs
Maybe this library contains good solution for global theming?
